### ISSUE TITLE
Custom Error Messages

### ISSUE THREAD

**Issue by JTraversa** [Swivel-Finance/gost#191]
With the introduction of custom errors last year, there are some optimizations we can add.

https://blog.soliditylang.org/2021/04/21/custom-errors/

Changing our reverts to custom errors should reduce bytecode size, and slightly reduce gas costs in non-reverting cases

**Comment by JTraversa** [comment]
Reference for gas costs: 

https://github.com/drgorillamd/error-gas-test

**Comment by robrobbins** [comment]
done
