### ISSUE TITLE
Grepping Governance Users

### ISSUE THREAD

**Issue by JTraversa** [Swivel-Finance/gost#193]
Aave:
https://etherscan.io/address/0xec568fffba86c094cf06b22134b23074dfe2252c

https://github.com/aave/governance-v2/blob/master/contracts/governance/AaveGovernanceV2.sol#L237

Compound:
https://etherscan.io/address/0xc0da02939e1441f497fd74f78ce7decb17b66529

https://github.com/compound-finance/compound-protocol/blob/master/contracts/Governance/GovernorBravoDelegate.sol#L232

Gitcoin:
https://etherscan.io/address/0xDbD27635A534A3d3169Ef0498beB56Fb9c937489

https://github.com/gitcoinco/governance/blob/main/contracts/GovernorAlpha.sol#L250

All of the above have two methods, vote and votebySig (or some variation) that we want to grep for and store any msg.sender of those method calls.

**Comment by robrobbins** [comment]
OK. i'll start collecting all of them.

should there be any criteria for inclusion / exclusion?
* number of calls
* some monetary amount based heuristic
* anything...

**Comment by JTraversa** [comment]
Since its just voting, we could require a # of tokens in a vote, but (to my understanding based on some Dune Analytics dashboards), the sets of voters are so small that I havent planned any more criteria other than having a successful vote tx.
