### ISSUE TITLE
Add protocol to marketplace mapping

### ISSUE THREAD

**Issue by JTraversa** [Swivel-Finance/gost#200]
In order to identify unique protocol/asset/maturity combinations, we need to add the protocol enum to the nested `Markets` mapping.
```
underlying => maturity 
address => uint256
-> 
protocol => underlying => maturity
uint8 => address => uint256
```

This ensures that we have unique identifiers for each market.

The fallout means a number of uint8 protocol params across methods in marketplace.sol, as well as accommodating those changes within Swivel.sol.

**Comment by sourabhmarathe** [comment]
This has been implemented (we went with a nested mapping to an array):
`mapping(address => mapping(uint256 => address[9])) public markets;`
