### ISSUE TITLE
Optimize loop iteration

### ISSUE THREAD

**Issue by JTraversa** [Swivel-Finance/gost#255]
We should make sure to check all our loops to implement the most gas efficient methodology:

```
uint256 length = array.length()
for (uin256 i=0; i < length;) {
    doStuff(array[i])
    unchecked { ++i; } 
}
```

**Comment by sourabhmarathe** [comment]
Is this issue specifically about the Illuminate contracts? If so, please mark it with the milestone `Pre-audit checklist`.

**Comment by JTraversa** [comment]
Its for both Illuminate and Swivel?

Swivel has more important loops that impact users, but we use a couple in Illuminate as well and could reduce our own gas use.

**Comment by sourabhmarathe** [comment]
To make sure it gets done for both, I'll make another ticket just for swivel.
