### ISSUE TITLE
Fee Patterns

### ISSUE THREAD

**Issue by JTraversa** [Swivel-Finance/gost#269]
## Rationale

Well... Fee structures are huge / important. Its uh... how you make money :)

There isnt another possible way for the protocol to make money at a base level without some form of fees, and fees on lending are the only rational source of fees in the protocol. 

There are other potential revenue sources available from the equivalent to PFOF or vote gauges but these are unreliable and/or far off.

If we dont want a fee we can turn it "off" somehow? But i think it should be in implementation. Uniswap for example has a protocol level fee that has just been off for years and yet to be enabled.

The goal should be to in general accrue some value to our contracts without bloating execution costs.

------------------------

## Implementing fees

One important thing overall, but especially in the implementation of fees is the reduction of the amount of transfers (due to their low transfer value in the first place).

The hope is that you can extract a fee, without necessitating any state changes or additional external calls.

The best way we've found to do this is transfer `amount` of funds to your contract, calculate a fee using that amount, and then execute the rest of the transaction using `amount-fee` as opposed to the raw `amount`.

This allows the contract to accrue fee value without requiring any additional calculation, so long as there is an additional method that aids with the withdrawal of fees. 

-----------------------

## Withdrawing fees

If the contract has fees in it, it needs to be able to withdraw them!

One could implement a `withdraw` method, similar to: [Swivel](https://github.com/Swivel-Finance/swivel/blob/main/contracts/v2/swivel/Swivel.sol#L401)

This allows the withdrawal of any generic ERC. That said, a generic withdraw represents significant risk without timelocks to protect users. One must also implement a per-token timelock that prevents arbitrary token withdrawals without the explicit knowledge of depositors.

The example above includes Swivel's timelock, but we should think about whether differences might be necessary.

-----------------------

**Comment by sourabhmarathe** [comment]
So under this model, we would custody the fees in the original contract that executes the lend operation, right?

As it currently stands, without fees, the user transfers their PTs to the `Lender` contract. After that, we go ahead an execute the lend operation depending based on the protocol.

With this method, we'd simply leave the fee amount inside the `Lender` contract, and then have a `withdraw` method. That makes sense to me, and does cut down on unnecessary transfers.

**Comment by JTraversa** [comment]
Yeeerp you got what I was suggesting. It leaves some minor vulnerability to the team withdrawing underlying PTs after the timelock, but imo thats acceptable? idk.

One way to deal with that risk might be to hardcode USDC as the withdrawn currency, and then provide a `tradeToUSDC` method that trades whatever fee (ETH, FEI, whatever) into USDC using uniswap.

That way the withdraw isnt arbitrary, just that trade on uniswap, and uniswap wont have PT pairs? 

That seems like a lot of effort / might be out of immediate scope?

**Comment by sourabhmarathe** [comment]
Well, in this case, the `withdraw` method is specifically for us right? So once we have custody over the relevant tokens, we can do that on our own right? 
I don't think I'm understanding this vulnerability.

**Comment by JTraversa** [comment]
The vulnerability isnt from *our* point of view but a user. And vulnerability isnt really the right word. Just admin/centralization risk.

From our point of view, yeah of course we are trustworthy.

A user might not agree though? And having an arbitrary method that can withdraw tokens breaks the immutability/safety of the contract from the user PoV

**Comment by sourabhmarathe** [comment]
In that case, it's a much more fundamental problem. It creates a huge honeypot for the `five dollar wrench`-style attacks that are not what we want. 

One way we can mitigate that is by having an attribute in the contract that tracks accumulated fees (e.g. `accumulatedFees`). We can reset to 0 whenever we call `withdraw`, and we can force the method to never be able to withdraw more than what has been accumulated in fees. This is much more trust-minimized as the user is aware there is a fee to pay to use the contract and its clear that the owner of the contract cannot have access to more than what has been accumulated in fees.

**Comment by sourabhmarathe** [comment]
Also have a ticket (#270) for the `withdraw` method, so this type of thing would be perfect for implementing in the PR for that ticket.

**Comment by JTraversa** [comment]
Conclusion from Sourabh & I's voice chat:

Unlike Swivel, we cannot assume all `underlying` in the contract are fees.

That said, like Sourabh mentioned above, we actually do need to track fees accrued with a mapping per underlying token address.
```
mapping (address => uint256) public accruedFees; (accrued?)
```

**Comment by robrobbins** [comment]
good stuff.  AFA the mapping for fees that are tracked over time for a given address, can we not just call it `fees` ?

**Comment by sourabhmarathe** [comment]
Now that fees have been implemented, I'm going to close this issue for now.
