### ISSUE TITLE
Implement a basic router contract for illuminate AMM pools

### ISSUE THREAD

**Issue by JTraversa** [Swivel-Finance/gost#298]
We'll be looking at integrating new YieldSpace pools, perhaps not into our repo, but they need to be tested regardless.

That said, theres the consideration for the addition for a `Router` contract.

The current yieldspace implementation we will be utilizing has a unique entry point per market. 

This is not ideal as it requires approvals on each individual market for LPs.

As an alternative we should implement a basic passthrough contract that takes `underlying` and `maturity`, looks up the pool, and passes all transfers on.

The router should be able to do a `transferFrom` from the user to the pool (i believe) and then execute with those funds already in the pool.

We can also consider something more advanced like deposits to / from compound from underlying, alongside the utilization of cTokens as the base/underlying token in the pool rather than the actual `underlying` itself.

**Comment by sourabhmarathe** [comment]
This was completed as part of adding `pools` to the marketplace contract.
