### ISSUE TITLE
Implement custom errors

### ISSUE THREAD

**Issue by JTraversa** [Swivel-Finance/gost#304]
We should implement custom errors for all of our current reverts, then take a quick look at them to review/audit what sort of data might be useful to bubble up in the errors themselves.

**Comment by sourabhmarathe** [comment]
I am currently blocked on this ticket due to `abigen` not supporting error types. Although we are able to compile the Solidity code, we cannot move them through our unit testing process.

**Comment by sourabhmarathe** [comment]
Turns out we need to upgrade `abigen` to `v1.10.10` to get this to work.
