### ISSUE TITLE
add generic eip-5095 redemption method (futureproofing yieldspace and others)

### ISSUE THREAD

**Issue by JTraversa** [Swivel-Finance/gost#323]
We should add a redemption function that doesnt necessarily cover the current protocols, but does cover eip-5095 given the general acceptance it seems to have gotten. 

This would pretty much just mean a method that calls: https://github.com/JTraversa/ERC-5095/blob/main/ERC5095.sol#L108

**Comment by sourabhmarathe** [comment]
Not sure if I understand this fully. Given that `zcToken` is a 5095, don't we essentially have this functionality with [`authRedeem`](https://github.com/Swivel-Finance/gost/blob/illuminate/test/redeemer/Redeemer.sol#L231)?
