### ISSUE TITLE
Final audit

### ISSUE THREAD

**Issue by sourabhmarathe** [Swivel-Finance/gost#354]
Leave your comments below @JTraversa.

**Comment by sourabhmarathe** [comment]
I think we should revisit the `redeem` method for Illuminate. I don't think it has been implemented correctly. Here's what it does now:
```
            // Get Illuminate's principal token
            IZcToken token = IZcToken(principal);

            // Make sure the market has matured
            if (block.timestamp < token.maturity()) {
                revert Invalid('not matured');
            }

            // Burn the prinicipal token from illuminate
            token.burn(o, amount);

            // Transfer the original underlying token back to the redeemer
            Safe.transferFrom(IErc20(u), lender, address(this), amount);
```
Instead, I think it should retrieve the zcToken (i.e. `IMarketPlace(marketPlace).markets(u, m, 0)`), and retrieve a different `amount` value (the `msg.sender`'s balance of zc tokens). Let me know what you think @JTraversa.

**Comment by sourabhmarathe** [comment]
I have not been able to find a signature matching yield protocol's `redeem` method in their repos:
`IYieldToken(principal).redeem(address(this), address(this), amount);`

The closest I could find is [this](https://github.com/yieldprotocol/yieldspace-tv/blob/fb2ca4374176362dc00935f2474bb9d153569769/src/interfaces/IERC4626.sol#L14), but it would mean that we have to update our Yield interface's signature.

**Comment by sourabhmarathe** [comment]
For the YieldSpace's `IPool`, the implementation is wrong. It should be based on the pool defined [here](https://github.com/yieldprotocol/yieldspace-interfaces/blob/main/IPool.sol#L21). We currently are using the wrong method names.

**Comment by JTraversa** [comment]
So you just referenced two different versions of their codebase.

We could add the ability to conform to both? Or ?

**Comment by sourabhmarathe** [comment]
Add natspec for `pools` and `markets` in MarketPlace.sol

**Comment by sourabhmarathe** [comment]
Implement a generic `redeem` method for 5095/4096.

**Comment by sourabhmarathe** [comment]
We just need to check on Sense protocol. Currently, we have a single interface `ISense`, but it appears that we may need to support multiple interfaces to get this to work. We just need to confirm that the maturity and swap method are in the same contract.
